### ISSUE TITLE
Woo Subscriptions V 6.0+ breaks WPCD

### ISSUE THREAD

**Issue by unakriti** [WPCloudDeploy/wp-cloud-deploy#101]
Hi,

I am seeing a weird issue that the WPCD public pages break inside the editor specifically while editing /cloud-apps and /cloud-servers/ . The error message is "Updating failed. This is not a valid JSON response". On the frontend, the UI is broken with a message "There has been a critical error on the website" . Here's a screenshot

![WPCD Woo Subscription Issue UI Breaks Screenshot from 2024-06-17 14-13-09](https://github.com/WPCloudDeploy/wp-cloud-deploy/assets/58072649/1c13bdd4-95db-4660-bd2b-ba98f8e49bed)

The issue goes away when I degrade the WooCommerce Subscriptions extension to Version 6.0. 

Issue persists with WPCD Version/s 5.8 and 5.7

Kind regards,

**Comment by ghost** [comment]
<img width="1628" alt="image" src="https://github.com/WPCloudDeploy/wp-cloud-deploy/assets/98357389/ba07a0c8-2433-492e-aaf4-2534411a3a54">


https://www.herdegenfuneralhome.com/obituaries/Nigel-Rasheed-Bahadur?obId=31617195

Nigel Bahadur no more ... its shocking. I wonder how would the WPCLOUDdeploy survive now :(

**Comment by unakriti** [comment]
> <img alt="image" width="1628" src="https://private-user-images.githubusercontent.com/98357389/340967148-ba07a0c8-2433-492e-aaf4-2534411a3a54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTY2MjgsIm5iZiI6MTcxODg1NjMyOCwicGF0aCI6Ii85ODM1NzM4OS8zNDA5NjcxNDgtYmEwN2EwYzgtMjQzMy00OTJlLWFhZjQtMjUzNDQxMWEzYTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA0MDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NmU2MTA2YTk5MmJmYWFkYWIzOTUyMTFiN2NiMjgyZGViYzg1OTNlY2IxZmViODdiNmUyYjdhYzc4Nzc5M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._RSWXkK48pk510QO1z5pIeh85ZhLfuRYxZFs3k5jt2U">
> https://www.herdegenfuneralhome.com/obituaries/Nigel-Rasheed-Bahadur?obId=31617195
> 
> Nigel Bahadur no more ... its shocking. I wonder how would the WPCLOUDdeploy survive now :(

Sad to read this. RIP Nigel.

**Comment by sunxiyuan** [comment]
You need to open debug mode and post the error output of this page

**Comment by unakriti** [comment]
> You need to open debug mode and post the error output of this page

Thanks much @sunxiyuan . 

I will park this issue for now - until the future of WPCD becomes clear.

Kind regards,

**Comment by qvdrei** [comment]
What will happen to WPCD now? I really want to get involved and continue to develop and market this product. I'm willing to hire developers and create a strategy to market it to broad market.

**Comment by eslam-dev** [comment]
Hello,

The issue seems to be due to WooCommerce Subscriptions. To solve the problem, navigate to the file at the following path:
woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-compatibility-functions.php
and modify the function named wcs_get_page_screen_id to return $object_type. Alternatively, you can replace it entirely with:

```
function wcs_get_page_screen_id( $object_type ) {
	return $object_type;
}

```
until a new version of WooCommerce Subscriptions is released that supports the latest version of WooCommerce.

We will continue updating the WPCD plugin on another repository. You can follow us and send any issues you encounter
[https://github.com/wpmts/wp-cloud-deploy](https://github.com/wpmts/wp-cloud-deploy)

**Comment by qvdrei** [comment]
> Hello,
> 
> The issue seems to be due to WooCommerce Subscriptions. To solve the problem, navigate to the file at the following path: woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-compatibility-functions.php and modify the function named wcs_get_page_screen_id to return $object_type. Alternatively, you can replace it entirely with:
> 
> ```
> function wcs_get_page_screen_id( $object_type ) {
> 	return $object_type;
> }
> ```
> 
> until a new version of WooCommerce Subscriptions is released that supports the latest version of WooCommerce.
> 
> We will continue updating the WPCD plugin on another repository. You can follow us and send any issues you encounter https://github.com/wpmts/wp-cloud-deploy

Great! Are you from Nigel's team? Do you know anyone from Nigel's team? Do you have acces to the Multi-Tenancy Module Or even the latest release "Momentum"? I want to join the project and market it to broad audience.

**Comment by eslam-dev** [comment]
@qvdrei 
We are not part of Nigel's team, but we did develop the multi-tenant feature with him in the beginning and also developed our own plugin for multi-tenancy
And tested it with a network of +9k sites and 4 servers

**Comment by nightcrawler123** [comment]
@qvdrei @eslam-dev this is modifying woo sub plugin! not the wpcd plugin. but it works i guess.

**Comment by qvdrei** [comment]
@eslam-dev 

Hmm .. did Nigel work alone? He asked for help from contractors like you? If he was a one man band, damn, he developed a lot alone...

Could you also tell me more about the multi-tenant plugin that you developed?

**Comment by eslam-dev** [comment]
@nightcrawler123 
The issue occurs due to a condition inside the Woo Sub plugin.

**Comment by eslam-dev** [comment]
@qvdrei 
Yes, he probably was working alone with the help of some contributors.

There is an additional plugin that enables multi-tenancy 
The idea is slightly different from WPCD 

Simple example

 our plugin creates a version control system on the internal server, so we don't issue a release that includes the entire WordPress as it is in WPCD.

We upload the versions inside the plugins or themes folder, and you can change the version from your admin panel or through WPCD. For example, in the versioning system for the WooCommerce plugin:

There is a folder named plugins, inside it a folder named woocommerce, and inside that folder are the versions like 9.0.0, 8.0.0, and so on. I can set the main version that runs on all sites and exclude the sites that have a custom version. For instance, if I change a site's version to 8.0.0, when an update is uploaded, it remains the same and does not change, but any other site that doesn't have a custom version specified will be updated.
```

  |__ plugins
    |__ woocommerce/
        |__  main/
        |__ 9.0.0/
        |__ 8.0.0/

```
