### ISSUE TITLE
OLS | Disable Welcome Page?

### ISSUE THREAD

**Issue by unakriti** [WPCloudDeploy/wp-cloud-deploy#41]
Hi,

I had noticed this on NGINX servers too. But there's nothing there for anyone to test / try. On OLS servers however, when I access the server IP address from a browser, it displays the OLS welcome page as shown below. Not sure how big or small this issue might be, but I am thinking anyone can play with the file upload and / or authentication testing.

![WPCD OLS Welcome Page on IP Address Screenshot from 2022-06-07 20-55-57](https://user-images.githubusercontent.com/58072649/172420748-f47c9ab7-7c4a-4c06-bf37-f1e5619fc3d8.png)

I see a solution suggested here ([DigitalOcean Forum](https://www.digitalocean.com/community/questions/how-to-disable-direct-ip-access-on-an-openlitespeed-droplet)). It requires enabling the Webserver Console port etc. Not complicated. But, I wonder whether this could be part of the default build.

PS: File I am testing is https://github.com/WPCloudDeploy/wp-cloud-deploy/archive/refs/heads/dev.zip

Kind regards,

**Comment by elindydotcom** [comment]
This should be resolved now on the dev branch.  The default page is now simply a message.

**Comment by unakriti** [comment]
Thank you @elindydotcom
