### ISSUE TITLE
Frontend | Duplicate Icons with Blocksy & Astra Themes

### ISSUE THREAD

**Issue by unakriti** [WPCloudDeploy/wp-cloud-deploy#43]
Hi,

I just noticed some of the server tabs have duplicate icons as highlighted in the frontend screenshot for ([Blocksy theme](https://pcm.wordpress.org/themes/blocksy/)) and also with [Astra theme](https://wordpress.org/themes/astra/). Such duplicate icons are visible on all layouts - Vertical, Horizontal, or Boxed.

![WPCD Dev Branch Testing Frontend Screenshot from 2022-06-10 09-06-47](https://user-images.githubusercontent.com/58072649/172986145-d2816d1d-5993-43ae-9575-97e4e2384300.png)

On the Twenty-Twenty Two theme and on the WPCD backend admin it looks okay but, if you suggest, I can check with the respective theme authors. Because it is only impacting styling of specific tabs (and not all), I thought to ask here first to see whether its a known issue or if there's something I might be missing.

PS: File I am testing is https://github.com/WPCloudDeploy/wp-cloud-deploy/archive/refs/heads/dev.zip

Kind regards,

**Comment by elindydotcom** [comment]
Huh.  Do those themes load font-awesome icons?  If so, do they have an option to turn them off?  If so, try that and see if the issue goes away.

**Comment by unakriti** [comment]
Blocksy Pro has an _option_ to do so but I am using the free version for testing. 

Here's the note from Blocksy authors - https://wordpress.org/support/topic/support-for-font-awesome-in-blocksy/ confirming they do not load font awesome CSS / icons by default.

Kind regards,

**Comment by elindydotcom** [comment]
We can try removing our icons from the front-end to see if the extra ones still show up.
There's a new option in the WHITE LABEL tab settings "disable tab icons on the front-end".
Curious if you turn that on, if any extra icons still show up.  Our icons should disappear so anything else that show up is likely to be from the theme.
Make sure you grab the latest dev files to see the new option.

**Comment by unakriti** [comment]
Thank you @elindydotcom 

Just tried the new option. It clears off not just the duplicate icons but all the icons from all tabs. 

Screenshot below please:
![WPCD Dev Branch Testing Frontend Icon Fix Screenshot Screenshot from 2022-06-13 13-10-39](https://user-images.githubusercontent.com/58072649/173304436-9024df3e-1b77-42d0-ab50-537083713e03.png)

Kind regards,

**Comment by elindydotcom** [comment]
Yeah, it should remove wpcd icons from all the tabs because the icon files are no longer being loaded.  So for these two themes you might just need to do without the icons (or try to see if some css can remove the duplicate icons.)  Weird how only some of them are duplicated and not all of them.

**Comment by unakriti** [comment]
Got it. 

Thank you.

**Comment by unakriti** [comment]
I looked this up last week and it was more like "fad fa-car-tilt". I did not notice icon duplication in the HTML. 

As a styling issue, its not a major issue, but It is somewhat weird.

**Comment by elindydotcom** [comment]
I took a closer look at this because I was really curious and figured out what was going on.

The issue is caused by a combination of things:

- The fonts used by the blocksy theme is larger than our defaults.  
- FontAwesome uses both the :before and :after pseudo elements.

Because of the size of the font, the :after pseudo element from fontAwesome is wrapping to the next line causing it appear as if two icons are there. 

The solution is to use some css around the the  icons to reduce their size:
Try playing with the  css around this:
`.rwmb-tab-nav` i

You might have to be more specific in the class but when it tried playing with it inside the browser inspector it resolved the issue.
