### ISSUE TITLE
Woo Addon | Automatic Subscription Cancellation

### ISSUE THREAD

**Issue by unakriti** [WPCloudDeploy/wp-cloud-deploy#49]
Hi,

**Cancel Subscription**: After a customer cancels a subscription, Woo status goes to Pending Cancellation with a Reactivate button visible to the customer under Woo -> My Account Dashboard. Can the status be updated to "cancelled" automatically without admin manually doing so?

PS: Files I am using - Beta versions of WPCD Core v5 and Woo Addon v3

Kind regards,

**Comment by elindydotcom** [comment]
Can you split this into two issues please?  They require two different solutions.

**Comment by elindydotcom** [comment]
The reason it goes to PENDING CANCEL is because there is still time left on the subscription.  Once the time runs out, WC will automatically switch it to cancelled.

**Comment by unakriti** [comment]
Makes good sense. 

Thank you.

**Comment by elindydotcom** [comment]
Closing this one then.
