### ISSUE TITLE
Woo Addon | Resubscribe Error

### ISSUE THREAD

**Issue by unakriti** [WPCloudDeploy/wp-cloud-deploy#50]
Hi

Once an order status is set to Cancelled, a customer sees a Resubscribe button in the My Account Dashboard. 

![WPCD Woo Resubscribe Workflow Screenshot from 2022-07-15 23-24-36](https://user-images.githubusercontent.com/58072649/179283912-9b35ccb0-cc10-406e-b39c-a0d4a1a24d90.png)

And, when that **Resubscribe button** is clicked, the process errors out because a region is not set (screenshot below):

![WPCD Woo Resubscribe Cart Error Screenshot from 2022-07-15 23-31-57](https://user-images.githubusercontent.com/58072649/179284264-583ff2a8-b08c-42a8-aae3-8edc1cdf0486.png)
 
It kind of breaks the customer's workflow inside Woo.

PS: Files I am using are the beta version of WPCD Core v5 and Woo Addon v3

Kind regards,

**Comment by elindydotcom** [comment]
Looks like we need to find a WCS hook to remove that button.

**Comment by unakriti** [comment]
Thanks.

The following works for me to disable the Resubscribe button: 

`add_filter( 'wcs_can_user_resubscribe_to_subscription', '__return_false', 100 );`

Kind regards,

**Comment by elindydotcom** [comment]
Yup.  We'll likely add something like that into the WC modules.

**Comment by elindydotcom** [comment]
Resolved in commit https://github.com/WPCloudDeploy/wp-cloud-deploy/commit/00afeee069a754e78aa663eff6243e6c7f160197
