### ISSUE TITLE
Woo Addon | Order Status "Processing"

### ISSUE THREAD

**Issue by unakriti** [WPCloudDeploy/wp-cloud-deploy#51]
Hi

Relates to - https://trello.com/c/8MZc9mkG/153-add-option-to-automatically-set-wc-orders-to-complete-after-provisioning-of-server-or-site

Can we automatically update the order status to Complete once a server has been _successfully_ deployed? At the moment, it continues to display as "Processing" and requires manual admin intervention. Screenshot below please:

![WPCD Update Woo Order Status Processing to Complete Screenshot from 2022-07-16 00-11-43](https://user-images.githubusercontent.com/58072649/179291651-422fda88-e42a-4e24-a756-68541fa049bf.png)

Kind regards,

**Comment by elindydotcom** [comment]
Reference: https://woocommerce.com/document/automatically-complete-orders/

Instead of hooking into the THANK YOU Page we'd need to hook into the WPCD deployment complete functions.

**Comment by elindydotcom** [comment]
@unakriti  - I believe this has been addressed in the WC add-on.
