### ISSUE TITLE
how to change default text when accessing server via IP

### ISSUE THREAD

**Issue by osidney** [WPCloudDeploy/wp-cloud-deploy#57]
I'm wanting to customize this text for the new servers, I found a script with the text, but when I change it and create a new server, it still shows the old texts. Could you tell me where should I change it? Thanks.
https://i.imgur.com/6PREK8q.png

**Comment by elindydotcom** [comment]
hmmm...there is only one place where it's located so chances are that you have the correct file (script 9999).  Is it possible the message is somehow cached in your browser?  Maybe try CTRL-F5 to force a full refresh?
