### ISSUE TITLE
V5 Default PHP Version 

### ISSUE THREAD

**Issue by backpackingseries** [WPCloudDeploy/wp-cloud-deploy#67]
Hi,

After a deployed a new Linode server, I set the default PHP version to 8.1. Screenshot below

![WPCD Default PHP on Server Screenshot from 2022-10-11 18-36-44](https://user-images.githubusercontent.com/32608044/195099726-4ad66ab0-12dc-4baa-a5bd-550dd5d352e5.png)

However, when I installed an app on that server, the app defaults to version 7.4 

![WPCD Default PHP on Apps Screenshot from 2022-10-11 18-37-55](https://user-images.githubusercontent.com/32608044/195100102-9c230987-c086-4607-a12d-91bc88c7f325.png)

Is this expected behaviour for apps to not inherit the PHP version from the server? If so, how to set PHP default version to 8.1 all across for new deployments?

Reference: https://wpclouddeploy.com/documentation/more/php-8-0-8-1-notes/

Kind regards,

**Comment by osidney** [comment]
I think this version of PHP is related to PHP CLI and not the site installation version in the panel.

**Comment by osidney** [comment]
Run on the server via SSH the php -v command and see if it will show the default version set on the tools screen.

**Comment by elindydotcom** [comment]
There are two locations where PHP is used and therefore each can be set a version independently.

There is a 'server' version  - which, as osidney mentioned is the equivalent of running a php script from the server command line.  This is what WP CLI uses.  

You can set this version in the SERVER → TOOLS tab.

Then there is the version that each site uses (the php pool).
You can set this version in the site PHP tab.

**Comment by backpackingseries** [comment]
Thank you @elindydotcom  That helps.

Few questions, if you do not mind please:

1. For now, if I want to be at the latest PHP versions, would these be PHP 7.4 on the server and PHP version 8.1 for WordPress apps?
2. For now, is there a way for me to define a default PHP version for new WordPress apps to be 8.1?
3. Lastly, is it possible to specify not to install certain PHP versions for new site deployments?

Kind regards,

**Comment by elindydotcom** [comment]
1. PHP 8.1 is the latest PHP version we install.  You can use it for both parts if you like - just make sure your themes and plugins are compatible with it.
2. Not without modifying the bash scripts (and likely the plugin code to update the meta storing the php version for the site)
3. Not without modifying the bash scripts.  (Right now all php versions prior to 7.4 are disabled by default anyway)

**Comment by backpackingseries** [comment]
Thanks much. That just leaves me with one observation @ 

> 1. PHP 8.1 is the latest PHP version we install.  You can use it for both parts if you like - just make sure your themes and plugins are compatible with it.

There's this text string carried forward since the previous WPCD version - a scary warning to not use versions other than version 7.4. 

![WPCD Default PHP on Server Screenshot from 2022-10-11 18-36-44](https://user-images.githubusercontent.com/32608044/195174048-333befe0-9e59-47e1-b521-31c515662144.png)

I guess this can be dropped now?

Kind regards,

**Comment by elindydotcom** [comment]
Yup, that does have to be updated.

**Comment by unakriti** [comment]
Sorry, just noticed the following. Screenshot from NGINX server deployment

![NGINX PHP Versions Screenshot from 2022-10-16 14-00-21](https://user-images.githubusercontent.com/58072649/196027992-fa2c4ea3-7988-422b-827a-1639a039d220.png)

On servers, PHP versions prior to 7.4 are also installed. Can these be dropped from V5 server installer?

Kind regards,

**Comment by elindydotcom** [comment]
No.  There are still thousands of sites out there that use these earlier versions.  But, they are disabled by default - only version 7.4 and higher are automatically enabled.
