### ISSUE TITLE
V5 Core | LS Cache Plugin

### ISSUE THREAD

**Issue by unakriti** [WPCloudDeploy/wp-cloud-deploy#68]
Hi,

I do not want any plugin to be installed during new site deployments and therefore have disabled the LS Cache option as shown below:

![WPCD Settings for Cache Disabled Screenshot from 2022-10-12 12-07-49](https://user-images.githubusercontent.com/58072649/195268894-324f72a5-c044-4e3e-bee1-62c5013d1c45.png)

However, during new site deployment, the installer continues to install the LS cache plugin

![WPCD Site Installer LS Cache Activated Message Screenshot from 2022-10-12 12-02-34](https://user-images.githubusercontent.com/58072649/195269033-1d985237-370d-4887-a067-2b9668a15d7e.png)

When I login to the new site, the LS Cache plugin is not seen! It makes me think - (1) either the installer messages are erroneous or (2) the plugin is actually installed and then removed which is not efficient anyway.

Kind regards,

**Comment by elindydotcom** [comment]
The plugin is installed as part of the core bash scripts.  Then when the core processes are completed, the after-action flags are checked and the plugin removed if needed.

**Comment by unakriti** [comment]
Thank you. Intuitively, I mistook the UI option as a hook to alter the script itself. 

Kind regards,

**Comment by unakriti** [comment]
Sorry, but just noticed it - screenshot below: since I have disabled the LS Cache option, I would expect the WP Cache record inside wp-config.php to be removed. 

![WPCD LS Cache Config in wp-config php Screenshot from 2022-10-12 12-47-00](https://user-images.githubusercontent.com/58072649/195276072-9ca0e8ce-14d5-48da-8f4d-0f132ee36428.png)

Or is this normal?

Kind regards,

**Comment by elindydotcom** [comment]
It should have no effect without the caching plugin installed.  Though I agree, it is a little sloppy.
