### ISSUE TITLE
V5 | OLS Manager UI 

### ISSUE THREAD

**Issue by unakriti** [WPCloudDeploy/wp-cloud-deploy#69]
Hi,

While trying to install the OLS manager, after I type in the username and password, I hit the enter key. Instead of installing the OLS manager, hitting the enter key updated the post. Is this expected behaviour or should hitting the enter key install the OLS manager instead? 

Kind regards,

**Comment by elindydotcom** [comment]
That's a quirk of the custom post type UI in WP.  Hitting enter will cause the UPDATE button to trigger.  Not sure if there's a good way to work around that.
