### ISSUE TITLE
V5 Core | Linux Crons for Sites

### ISSUE THREAD

**Issue by unakriti** [WPCloudDeploy/wp-cloud-deploy#70]
Hi,

I am playing with Linux cron intervals for deployed sites. Screenshot below for 5 minutes interval:

![WPCD Linux Cron for Sites Screenshot from 2022-10-12 19-49-43](https://user-images.githubusercontent.com/58072649/195368872-8293882e-6b4d-461a-b82c-3e0a317f069a.png)

Unless I am missing something obvious, when I verify with a crontab -e terminal command, the output does not differ whether the cron interval is set to 1, 2, or 5 minutes.  Screenshot below:

![WPCD crontab -e Output Screenshot from 2022-10-12 19-54-17](https://user-images.githubusercontent.com/58072649/195369656-22c02d4a-4138-49d3-8785-f57126acc252.png)

I was hoping to see the interval changes reflect in there. Is this expected behaviour? 

Kind regards,

**Comment by elindydotcom** [comment]
Yes, that is expected behavior.  The crontab entry you're highlighting is a bootstrap script.  The actual logic for the times for individual sites are embedded in configuration files are used by that script.

**Comment by unakriti** [comment]
Ah okay, I only looked at the asterisks and not the latter part of the cron job. :)

Thanks for the clarification.
