### ISSUE TITLE
Disable < PHP 8.0 version installation

### ISSUE THREAD

**Issue by Hans-101** [WPCloudDeploy/wp-cloud-deploy#93]
**To Reproduce**

When deploying a new server, PHP 5.6, 7.1, 7.2, 7.3 & 7.4 are automatically installed.

**Expected behavior**

Possibly, in edge cases, those versions are needed, however, in 2023 anything below 8.0 is insecure, and outdated.
**It would be great to pre-specify the to install PHP versions for new server deployments. Or at least, modify the script as work-around**

**Screenshots & Videos**
![image](https://github.com/WPCloudDeploy/wp-cloud-deploy/assets/83392076/62c1da8a-031b-41f2-b8bd-b5d2a0a2ceaa)

**Comment by SuperHondo** [comment]
Can you retype slowly with correct spellings, as I couldn't make out what you meant ?

**Comment by Hans-101** [comment]
I'm not following where the grammar issues are, but let me try:
The idea is to avoid installing PHP versions prior to 8.0, or being able to select which versions are to be installed when a new server is deployed.

**Comment by SuperHondo** [comment]
> I'm not following where the grammar issues are, but let me try: The idea is to avoid installing PHP versions prior to 8.0, or being able to select which versions are to be installed when a new server is deployed.

Pardon me, didnt mean to demean your post. Thanks for updating.

**Comment by Hans-101** [comment]
I didn’t have my coffee yet 😵‍💫

**Comment by elindydotcom** [comment]
This has been completed as of 5.4.0
