### ISSUE TITLE
Tooltips partially visible

### ISSUE THREAD

**Issue by Hans-101** [WPCloudDeploy/wp-cloud-deploy#94]
**Describe the bug**
Some tooltips are only partially visible, as the sidebar overlaps them.

**Expected behavior**
Offset them a little, so they are not covered by the sidebar:

**Screenshots & Videos**
![image](https://github.com/WPCloudDeploy/wp-cloud-deploy/assets/83392076/0fccd4e6-8a04-4dc8-a400-c0a2abd22ef6)

**Desktop (please complete the following information):**
 - OS: [OSX]
 - Browser [Chrome]
 - Version [114.0.5735.133]

**Comment by SuperHondo** [comment]
+1 : I too noticed those but over looked. Hope it gets rectified by team WPCD.

**Comment by nightcrawler123** [comment]
+1 same here noticed it creeping in the recent 2 versions

**Comment by elindydotcom** [comment]
Fixed - finally.  v5.5.0
