### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: 3 arguments are required, 2 given

### ISSUE THREAD

**Issue by cmhello** [WPCloudDeploy/wp-cloud-deploy#98]
`Fatal error: Uncaught ArgumentCountError: 3 arguments are required, 2 given in /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/tabs/statistics.php:185 Stack trace: #0 /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/tabs/statistics.php(185): sprintf() #1 /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/tabs/statistics.php(152): WPCD_WORDPRESS_TABS_STATISTICS->get_statistics_fields() #2 /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/tabs/tabs.php(60): WPCD_WORDPRESS_TABS_STATISTICS->get_actions() #3 /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/tabs/statistics.php(92): WPCD_WORDPRESS_TABS->get_fields_for_tab() #4 /wp-includes/class-wp-hook.php(310): WPCD_WORDPRESS_TABS_STATISTICS->get_tab_fields() #5 /wp-includes/plugin.php(205): WP_Hook->apply_filters() #6 /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/traits/traits-for-class-wordpress-app/metaboxes-app.php(68): apply_filters() #7 /wp-includes/class-wp-hook.php(310): WPCD_WORDPRESS_APP->add_meta_boxes() #8 /wp-includes/plugin.php(205): WP_Hook->apply_filters() #9 /wp-content/plugins/wp-cloud-deploy/includes/core/apps/class-wpcd-app.php(169): apply_filters() #10 /wp-includes/class-wp-hook.php(310): WPCD_APP->register_app_metaboxes() #11 /wp-includes/plugin.php(205): WP_Hook->apply_filters() #12 /wp-content/plugins/meta-box/inc/core.php(25): apply_filters() #13 /wp-includes/class-wp-hook.php(310): RWMB_Core->register_meta_boxes() #14 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters() #15 /wp-includes/plugin.php(517): WP_Hook->do_action() #16 /wp-settings.php(632): do_action() #17 /wp-config.php(98): require_once('...') #18 /wp-load.php(50): require_once('...') #19 /wp-blog-header.php(13): require_once('...') #20 /index.php(17): require('...') #21 {main} thrown in /wp-content/plugins/wp-cloud-deploy/includes/core/apps/wordpress-app/tabs/statistics.php on line 185`

**Comment by cmhello** [comment]
wp-cloud-deploy 5.4.0

**Comment by elindydotcom** [comment]
@cmhello - new installation of WPCD?  Or upgrading an existing installation?

**Comment by cmhello** [comment]
@elindydotcom new installation of WPCD 5.4.0

**Comment by wpcloudpanel** [comment]
We just went through the entire installation process and could not duplicate this.

- We created a new WP site and updated the nginx configuration for timeouts, etc.
- We installed wpcd
- We connected to digitalocean using the wizard
- Added a new server
- Added a new site
- Went to the site statistics tab.

No errors were thrown.

Is there any other information you can add to the issue about your scenario that might help us duplicate the issue?  If not, perhaps a video - maybe we can spot something in there?

**Comment by cmhello** [comment]
@wpcloudpanel 
You can access the panel of any website application, click the [statistics] tab, and then click the [Re-calculate] button under "DISK SPACE". An error will be reported after execution.

**Comment by wpcloudpanel** [comment]
@cmhello - I just tried that on the new installation and didn't get an error.  I also tried it on an existing install that was upgraded and didn't get an error either.

**Comment by cmhello** [comment]
I'm very sorry. This was my mistake. There were some errors in the Chinese language pack I translated, which caused me to encounter the error.

Thank you for your prompt reply. I am very interested in your product and am testing it to see if it meets my needs.
